evaluate: True

result_path: experiments/FBIL_EVAL
manual_seed: 1
print_freq: 20
resume_path: result_path

model:
    freeze_bn: True
    backbone:
        arch: slowfast101
        learnable: True
        pretrain:
            path: pretrained/SLOWFAST_R101_K700.pth.tar
        kwargs:
            alpha: 4
            beta: 0.125
    neck:
        type: basic
        kwargs:
            bbox_jitter:
                num: 1
                scale: 0.075
            num_classes: 60
            multi_class: True
            
    head:
        type: fbil
        kwargs:
            width: 2304
            roi_spatial: 7
            num_classes: 60
            act: softmax
            e_depth: 3
            c_depth: 3
            l_depth: 3
            local_beta: 0.9
            local_delta: 0.2
            global_beta: 0.2
            global_delta: 1.0

loss:
    type: ava_criterion
    kwargs:
        pose_softmax: True

train:
    root_path: your_path
    annotation_path: annotations/ava_train_v2.2_with_fair_0.9.pkl
    batch_size: 2
    workers: 4
    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: RandomHorizontalFlip
          - type: ToTensor
            kwargs:
                norm_value: 1.
          - type: Normalize
            kwargs:
                mean: [110.63666788, 103.16065604, 96.29023126]
                std: [38.7568578, 37.88248729, 40.02898126]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    n_epochs: 8
    val_freq: 1
    save_freq: 1

    optimizer:
        type: SGD
        kwargs:
            momentum: 0.9
            weight_decay: 0.0000001
            nesterov: True

    scheduler:
        type: step
        milestone_epochs: [4, 6]
        lr_mults: [0.1, 0.1]
        base_lr: 0.0015
        warmup_lr: 0.012
        warmup_epochs: 1

val:
    root_path: your_path
    annotation_path: annotations/ava_val_v2.2_fair_0.85.pkl
    batch_size: 1
    workers: 4
    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: ToTensor
            kwargs:
                norm_value: 1.
          - type: Normalize
            kwargs:
                mean: [110.63666788, 103.16065604, 96.29023126]
                std: [38.7568578, 37.88248729, 40.02898126]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    with_label: False
    eval_mAP:
        labelmap: annotations/ava_action_list_v2.2_for_activitynet_2019.pbtxt
        groundtruth: annotations/ava_val_v2.2.csv
        exclusions: annotations/ava_val_excluded_timestamps_v2.2.csv
